### ISSUE TITLE
LPS Tools does not let me firmware updating

### ISSUE THREAD

**Issue by santiagorg2401** [bitcraze/lps-tools#14] opened 2020-08-14 18:07 UTC
Hi, 
I am trying to update the LPS Nodes firmware but the GUI does not let me do it, the Update button does not work.
![image](https://user-images.githubusercontent.com/52050852/90279609-255e7d00-de2f-11ea-836e-7ba48633f7cc.png)

**Comment by krichardsson** [comment] 2020-08-17 14:00
Hi!

It looks like you are on linux. Have you set the access rights as described here https://github.com/bitcraze/lps-tools#usb-access-right-on-linux ?

**Comment by MonaNekoWR** [comment] 2021-05-01 08:00
I also met this problem.
My OS: Mac OS 11.2.3 with Apple Silicon M1
Dose this OS also need to set access?
And if so, how to set access?

**Comment by krichardsson** [comment] 2021-05-03 10:17
Hi @MonaNekoWR
I can confirm that I also have a problem with flashing from the LPS tool. This problem seems to be different from what this issue was about originally so I have created a new one, #18.

**Comment by krichardsson** [comment] 2021-05-03 12:51
@MonaNekoWR There is no need to set access for USB on OSX as far as I know.

Let's try to figure out what is happening, I have 2 questions:
1. Does anything happen at all when connecting the anchor in DFU mode?
2. Does anything happen at all when connecting the anchor and NOT holding down the DFU button?

**Comment by MonaNekoWR** [comment] 2021-05-03 13:47
@krichardsson 
> 1. Does anything happen at all when connecting the anchor in DFU mode?
It shows everything well in my computer.
> 2. Does anything happen at all when connecting the anchor and NOT holding down the DFU button?
Nothing happened, but I can't configure node by LPS  configuration tool. The Apply button is gray.

**Comment by krichardsson** [comment] 2021-05-03 15:33
For 1. LPS-tools uses pyusb, and pyusb in turn uses libusb. It turned out that even though this used to work on my machine something was broken, maybe by an update of OSX? To fix it I uninstalled libusb and pyusb then reinstalled libusb first and then pyusb. 
To install lib usb use brew: ```brew install libusb```
To install pyusb use pip: ```pip install pyusb```

For 2. LPS-tools uses pyserial. I don't think LPS-tools would start without pyserial, but maybe it is worth trying to reinstall it.
```pip uninstall pyserial```
```pip install pyserial```

Also make sure you have the latest python (3.9.1 I think). Apple moved libraries around in the file system and the first python version that supports this new structure is 3.9.

**Comment by krichardsson** [comment] 2021-05-03 15:34
As a clarification, everything seems to work fine on OSX (after a reinstall of libusb and pyusb)

**Comment by MonaNekoWR** [comment] 2021-05-04 07:34
Well, things go just like this which means I need a lower version pyserial.
```
Collecting pyserial
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Installing collected packages: pyserial
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

lpstools 0.1 requires pyserial==3.4, but you'll have pyserial 3.5 which is incompatible.
Successfully installed pyserial-3.5
```

**Comment by krichardsson** [comment] 2021-05-04 12:46
Great!
I'll close the issue. Feel free to re-open it if any problems persist

**Closed by krichardsson** 2021-05-04 12:46 UTC
